### ISSUE TITLE
Check bounds on overlap index

### ISSUE THREAD

**Issue by zeeev** [PacificBiosciences/pb-falcon-phase#1]
Currently, the falcon-phase binary assumes that the indices in the overlap index file are correct. When provided an index out of bounds falcon-phase seg-faults. It is easy to check for bounding issues while parsing the overlap index file.

@skingan I've attached a test dataset that generates an incorrect overlap index file. I think we should also correct the script that generates the overlap index?
```
Before:
000000F	2,0	0:2
000001F	4,1	1:4

Correct:
000000F	2,0	0:2
000001F	3,1	1:3
```

[test_data.zip](https://github.com/PacificBiosciences/pb-falcon-phase/files/2677173/test_data.zip)

**Comment by pb-cdunn** [comment]
For a solution, do you suggest clipping to a boundary at line 502? Or skipping overlaps that exceed the bounds?

And where would we learn the bounds for the matrix?

Alternatively, if we try to clip as we generate `ov_index.txt`, how do we know the bounds given only `AB_pairs.txt` and `minced.fasta`?

**Comment by zeeev** [comment]
Hi @pb-cdunn,

Thank you for looking at this issue. The fc_primary_contig_index.pl script, is feeding incorrect indices, to falcon-phase. I can check the bounds within falcon-phase and exit with an informative error, which wouldn't take much work.

To answer you question, the index cannot exceed the number of entries in the minced fasta ../minced_fasta/minced.fasta. i.e. wc -l ../minced_fasta/minced.fasta.fai

Does that make sense to you?

**Comment by pb-cdunn** [comment]
I think the fix is as simple as this:
```diff
--- bin/fc_primary_contig_index.pl
+++ bin/fc_primary_contig_index.pl
@@ -42,7 +42,7 @@ while (my $line = <FAI>) {
         $fai_hash{$line_array[0]} = $index;
         $index++;
 }
-$fai_hash{$line_array[0]} = $index;
+#$fai_hash{$line_array[0]} = $index;
```
That definitely outputs the right thing in this particular testcase.

**Comment by skingan** [comment]
Yes, that looks right to me.
