### ISSUE TITLE
Phased genetic map instead of Hi-C

### ISSUE THREAD

**Issue by Sea-bar** [PacificBiosciences/pb-falcon-phase#6]
Greetings, 
I have a phased genetic map, and a Hicanu assembly containing primary contigs and haplotigs. Can I modify FALCON-phase parameters to use these data types, instead of a FALCON-unzip assembly with HiC?

**Comment by pb-cdunn** [comment]
I don't think that would be very easy. But maybe @zeeev has a thought.

**Comment by zeeev** [comment]
Hi @Sea-bar,

This is a logical request, but unfortunately adapting the input would be very painful. No plans on integrating other sources of data.

--Zev
